definitions:
  controllers.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  usecases.AuthUserInput:
    properties:
      email:
        example: juliano@test.com
        type: string
      password:
        example: P4ssw0rd!
        type: string
    required:
    - email
    - password
    type: object
  usecases.AuthUserOutput:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjA4Mjk5MDAsInN1YiI6IjUwNmU4Mjc4LTNiMzktNDI0ZS04NGU4LWMzYTE4NzcwNzBiNyJ9.AlUCK04QFIcGwlRw0e29fRMYlzZ3V979EH3pWlFVA1g
        type: string
    required:
    - token
    type: object
  usecases.GetBookingGuestsOutput:
    properties:
      birth_date:
        example: "1990-01-01T00:00:00Z"
        type: string
      document_number:
        example: "12345678901"
        type: string
      document_type:
        example: CPF
        type: string
      email:
        example: johndoe@example.com
        type: string
      gender:
        example: Masculino
        type: string
      guest_id:
        example: 326ebf92-1597-4850-b21e-3c1c8d7e5c6e
        type: string
      last_name:
        example: Doe
        type: string
      name:
        example: John
        type: string
      whatsapp:
        example: "43888888888"
        type: string
    type: object
  usecases.GetBookingOutput:
    properties:
      booking_id:
        example: 71cf737c-228e-4973-8197-3c5cf83454a9
        type: string
      check_in:
        example: "2024-06-01T11:00:00Z"
        type: string
      check_out:
        example: "2024-06-04T13:00:00Z"
        type: string
      email:
        example: juliano@test.com
        type: string
      guests:
        items:
          $ref: '#/definitions/usecases.GetBookingGuestsOutput'
        type: array
      overnight:
        example: 3
        type: integer
      room_category:
        example: Standard
        type: string
      total_amount:
        example: 300
        type: number
      total_guests:
        example: 2
        type: integer
      whatsapp:
        example: "43999999999"
        type: string
    type: object
  usecases.GetBookingsOutput:
    properties:
      booking_id:
        example: 71cf737c-228e-4973-8197-3c5cf83454a9
        type: string
      check_in:
        example: "2024-06-01T11:00:00Z"
        type: string
      check_out:
        example: "2024-06-04T13:00:00Z"
        type: string
      overnight:
        example: 3
        type: integer
      room_category:
        example: Standard
        type: string
      total_amount:
        example: 300
        type: number
      total_guests:
        example: 2
        type: integer
    type: object
  usecases.GetRoomsOutput:
    properties:
      capacity:
        example: 4
        type: integer
      category:
        example: Premium
        type: string
      price:
        example: 2000
        type: number
      room_id:
        example: 71cf737c-228e-4973-8197-3c5cf83454a9
        type: string
    type: object
  usecases.MakeBookingInput:
    properties:
      check_in:
        example: "2024-06-01T11:00:00Z"
        type: string
      check_out:
        example: "2024-06-04T13:00:00Z"
        type: string
      email:
        example: juliano@test.com
        type: string
      room_id:
        example: "1"
        type: string
      total_guests:
        example: 2
        type: integer
      whatsapp:
        example: "43999999999"
        type: string
    required:
    - check_in
    - check_out
    - email
    - room_id
    - total_guests
    - whatsapp
    type: object
  usecases.MakeBookingOutput:
    properties:
      booking_id:
        example: 71cf737c-228e-4973-8197-3c5cf83454a9
        type: string
      overnight:
        example: 3
        type: integer
      total_amount:
        example: 300
        type: number
    type: object
  usecases.RegisterRoomInput:
    properties:
      capacity:
        example: 4
        type: integer
      category:
        example: Premium
        type: string
      price:
        example: 2000
        type: number
    required:
    - capacity
    - category
    - price
    type: object
  usecases.RegisterRoomOutput:
    properties:
      room_id:
        example: 71cf737c-228e-4973-8197-3c5cf83454a9
        type: string
    type: object
  usecases.RegisterUserInput:
    properties:
      email:
        example: juliano@test.com
        type: string
      name:
        example: Juliano
        type: string
      password:
        example: P4ssw0rd!
        type: string
    required:
    - email
    - name
    - password
    type: object
  usecases.RegisterUserOutput:
    properties:
      id:
        example: 506e8278-3b39-424e-84e8-c3a1877070b7
        type: string
    required:
    - id
    type: object
host: fasttrip.onrender.com
info:
  contact: {}
  description: Fasttrip API permite executar operações para cadastrar quartos, fazer
    reservas, checkin e checkout.
  title: Fasttrip API
  version: v1.7.1
paths:
  /auth_user:
    post:
      consumes:
      - application/json
      description: Autentica usuário
      parameters:
      - description: AuthUserInput
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.AuthUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.AuthUserOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Autentica usuário
      tags:
      - user
  /get_booking/{booking_id}:
    get:
      description: Pegar reserva
      parameters:
      - description: Insert you bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Booking ID
        in: path
        name: booking_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecases.GetBookingOutput'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Pegar reserva
      tags:
      - booking
  /get_bookings:
    get:
      description: Pegar reservas
      parameters:
      - description: Insert you bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecases.GetBookingsOutput'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Pegar reservas
      tags:
      - booking
  /get_rooms:
    get:
      description: Pegar quartos
      parameters:
      - description: Insert you bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecases.GetRoomsOutput'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Pegar quartos
      tags:
      - room
  /make_booking:
    post:
      consumes:
      - application/json
      description: Faz nova reserva
      parameters:
      - description: Insert you bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: MakeBookingInput
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.MakeBookingInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/usecases.MakeBookingOutput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Faz nova reserva
      tags:
      - booking
  /register_room:
    post:
      consumes:
      - application/json
      description: Registra novo quarto
      parameters:
      - description: Insert you bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: RegisterRoomInput
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.RegisterRoomInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/usecases.RegisterRoomOutput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Registra novo quarto
      tags:
      - room
  /register_user:
    post:
      consumes:
      - application/json
      description: Registra novo usuário
      parameters:
      - description: RegisterUserInput
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.RegisterUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecases.RegisterUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Registra novo usuário
      tags:
      - user
swagger: "2.0"
